version: "3.1"
services:
  postgres:
    image: postgres:14.5
    networks:
      default:
        aliases:
          - postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@iphantasmic.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5431:80"

  user-service:
    build: .
    image: user
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - DB_CONN_STRING=postgresql://admin:admin@postgres_db
    volumes:
      - .:/app
    networks:
      default:
        aliases:
          - user_service
    ports:
      - "8080:8080"